import:
  - ~/.config/alacritty/nord.yml

env:
  TERM: xterm-256color

font:
  normal:
    family: Jetbrains Mono NL
    # family: Fira Code
    # family: Dejavu Sans Mono
  size: 13.5

window:
   dimensions:
     columns: 100
     lines: 24

