font:
  size: 14
env:
  TERM: xterm-256color
# key_bindings:
#   - { key: J,        mods: Alt,     chars: "\x1bj"                       }
#   - { key: K,        mods: Alt,     chars: "\x1bk"                       }

# # Colors (Gruvbox dark)
# colors:
#   # Default colors
#   primary:
#     background: '0x1d2021'
#     foreground: '0xebdbb2'

#   # Normal colors
#   normal:
#     black:   '0x282828'
#     red:     '0xcc241d'
#     green:   '0x98971a'
#     yellow:  '0xd79921'
#     blue:    '0x458588'
#     magenta: '0xb16286'
#     cyan:    '0x689d6a'
#     white:   '0xa89984'

#   # Bright colors
#   bright:
#     black:   '0x928374'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xebdbb2'

# Colors (tpope)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xaaaaaa'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xaa0000'
    green:   '0x00aa00'
    yellow:  '0xaa5522'
    blue:    '0x0000ee'
    magenta: '0xaa00aa'
    cyan:    '0x00aaaa'
    white:   '0xaaaaaa'

  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xff4444'
    green:   '0x44ff44'
    yellow:  '0xffff00'
    blue:    '0x5c5cff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'


